### ISSUE TITLE
How to dynamically set the request port in the `hawk` settings?

### ISSUE THREAD

**Issue by tiagoalves** [hapijs/hapi-auth-hawk#16]
Our service is running behind HAProxy that offloads SSL connections. So, even for https requests, our service will always use unsecure connections between HAProxy and the Hapi server. So, Hawk will assume we're using port 80.

We've tried the solutions recommend [here](https://github.com/hueniverse/hawk/issues/79) (the `server.ext('onPreAuth', function(request, next) {})` part) but that didn't seem to work. The Hawk module checks for `request.connection.encrypted` and `request.headers['host']` by default to understand which port is being used. However, I'd like to avoid setting `request.connection.encrypted` to `true` and appending `':443'` to  `request.headers['host']` since I don't know the consequences of that. Setting `request.url.port`, as suggested, or `request.port` didn't have any effect.

I know there's the `hawk` settings object which can be set to override the port. However, that object is static and I don't see how I can set the port on a per request basis. We don't want to assume that all requests are done through https.

Could we change the `hawk` settings property to optionally be a function that receives the incoming `request` as argument and returns a dynamically created object as the result? Do you have any other suggestion on how to tackle this?

Thank you!

**Comment by dannycoates** [comment]
I'm not sure about setting the port dynamically. My gut feeling is that its not a good idea, but it may very well be fine. I'd rather not think too hard about it unless its the only option.

My first thought is that if your situation allows it I'd have my app server listen on two ports, one for plain HTTP and the other for the proxied HTTPS, and configure each for hawk statically. I think there's less of a chance of getting requests mixed up that way.

**Comment by hueniverse** [comment]
All you need to do is pass `hawk.port` setting to the plugin with the actual port clients will be using. You don't need to set it per request because all request for a given connection should come from a single source. If you are proxying multiple outside ports into a single hapi connection, consider splitting that into multiple connections. You can then load the auth plugin separately for each connection using `server.select()` with the right port setting.

**Comment by tiagoalves** [comment]
Oh, that's great. Thanks to both of you.
