### ISSUE TITLE
Check for artifact.hash before listening on payload and calculating hash

### ISSUE THREAD

**Issue by hueniverse** [hapijs/hapi-auth-hawk#25]
Before this: https://github.com/hapijs/hapi-auth-hawk/blob/master/lib/index.js#L40

It's wasteful to calculate hash when we know if the client even sent it.

**Comment by zoe-1** [comment]
Want to clarify what we are after here? 
1) Hawk.server.authenticate -- authenticates the request. 
2) After authentication, if a hash was present in request, `artifacts.hash` will exist. 
3) if it exists, then we begin the `request.once('peek'.....)` logic. 
4) if not exists, we skip the request.once('peek') logic making the program more efficient.
It avoids executing `Hawk.crypto.initializePayloadHash`.

Correct? Built something like this and have all tests passing. 
Before submitting a PR just want to confirm I am grasping the issue correctly. 
Below is a sample of what I am thinking here.
Please advise.

``` JavaScript
Hawk.server.authenticate(request.raw.req, settings.getCredentialsFunc, settings.hawk, (err, credentials, artifacts) => {

                if (!err && artifacts.hash) {

                    request.once('peek', (chunk) => {

                        const payloadHash = Hawk.crypto.initializePayloadHash(request.auth.credentials.algorithm, request.headers['content-type']);
                        payloadHash.update(chunk);

                        request.on('peek', (chunk2) => {

                            payloadHash.update(chunk2);
                        });

                        request.once('finish', () => {

                            request.plugins['hapi-auth-hawk'] = { payloadHash: Hawk.crypto.finalizePayloadHash(payloadHash) };
                        });
                    });
                }

                const result = { credentials, artifacts };

                if (err) {
                    return reply(err, null, result);
                }

                return reply.continue(result);
            });

```

**Comment by hueniverse** [comment]
@zoe-1 missed this. Yes, this was correct (but needs to be adjusted to latest). Still want to PR?
