### ISSUE TITLE
Plugin does not support vhosts

### ISSUE THREAD

**Issue by red-0ne** [hapijs/hapi-auth-hawk#30]
Having set up a Hapi server with multiple vhosts where each one registers `hapi-auth-hawk`; The server refuses to start stating that `Plugin hapi-auth-hawk already registered in ...` .

Also, adding `multiple: true` to `hapi-auth-hawk`'s `register.attributes` on both vhosts (each one has its owns node_modules); the server ends with `Authenticaton scheme name already exists: hawk`.

How am I supposed to configure the auth of each vhost?

**Comment by hueniverse** [comment]
I assume you don't need this anymore but if you do, please ping me.
