### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by hueniverse** [hapijs/hapi-auth-hawk#31]
This project is not maintained up to hapi.js standards.

**Comment by hueniverse** [comment]
@dannycoates any objections to passing this to a new maintainer?

**Comment by dannycoates** [comment]
None at all. Perhaps @rfk could help find a new one?

**Comment by rfk** [comment]
thanks @dannycoates - I'll bring this up with folks on my team since it's a pretty important dependency for us, but I probably won't get around to it until next week.

**Comment by hueniverse** [comment]
I think @mtharrison is planning on taking over.
