### ISSUE TITLE
hapi v17 support

### ISSUE THREAD

**Issue by hueniverse** [hapijs/hapi-auth-hawk#32]

**Comment by mtharrison** [comment]
Happy to take this on, if you want to assign me.

**Comment by hueniverse** [comment]
This issue or the whole module?

**Comment by mtharrison** [comment]
This issue.

**Comment by hueniverse** [comment]
Sounds good either way. Still need to find new maintainer for this.

**Comment by mtharrison** [comment]
I will take the module too in that case 😄

**Comment by Samueljoli** [comment]
@mtharrison Hey how's it going with the upgrade? Make any progress? I don't mind picking this up if you haven't
